### ISSUE TITLE
Default Z value if not passed?

### ISSUE THREAD

**Issue by flamendless** [Nikaoto/DEEP#1]
Hey, really like this library, although it's fairly new, i would like to point out somethings.

1. using deep:print("something",32,32) --note, no Z, this is not drawn.
2. change "queue" name? It's really hard to type that always, without making a few mistakes.

**Comment by flamendless** [comment]
I will pull some requests about my suggestion.

**Comment by Nikaoto** [comment]
When calling any function in DEEP,  like `deep:print("something", 32, 32)` , any missing arguments should default to the variables given in the defaults table:
```Lua
local defaults = {
	z = 1, r = 0, 
	sx = 1, sy = 1, 
	ox = 0, oy = 0, 
	kx = 0, ky = 0, 
	color = {255, 255, 255, 255}
}
```
Also, I have merged your pull request, thank you!
